#Name of the application
spring:
  application:
    name: cash36-ebics
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  output: 
    ansi: 
      enabled: ${CASH36_ANSI:ALWAYS}
      
server:
  port: ${CASH36_SERVER_PORT:8093}
  servlet:
    context-path: /ebics

springdoc:
   swagger-ui:
      disable-swagger-default-url: true
      

ebics:
  # for different java version, you can use ebics-cli as docker in docker- see 
  # https://hub.docker.com/repository/docker/e36io/ebics-cli
  entrypoint: ${CASH36_EBICS_ENTRYPOINT:java -cp ./ebics-cli.jar org.kopi.ebics.client.EbicsClient}
  mode: ${CASH36_EBICS_MODE:proxy}
  outputDir: ${CASH36_EBICS_OUTPUTDIR:./out}
  peggingAccount: 
     iban: CH21 0830 7000 2895 3732 0
     bic: HYPLCH2257B
  ignoreAccounts:
    # do not integrate information of these accounts into json responses
    #- "CH2108307000289537320"
  proxy:
     # sends this ebics file when simulate is called
     statement: ${CASH36_EBICS_STATEMENT:simulated-account-statements.zip}
           
logging:
  level:
     org.springframework: WARN
     io.element36: TRACE
     ROOT: WARN      